---
- hosts: all
  become: no
  vars:
    kofa_version: 1.5
    ansible_python_interpreter: /usr/bin/python2.7
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400
    become: yes

  - name: Aptitude safe-upgrade
    apt: upgrade=safe
    become: yes

  - name: Install system packages
    become: yes
    package:
      name={{ item }}
      state=present
    with_items:
      - libssl-dev
      - libffi-dev
      - python2.7-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - python-virtualenv
      - libjpeg-dev
      - libfreetype6-dev
      - libtiff-dev
      - libopenjpeg-dev
      - wget
      - git

  - name: Check freetype2 link
    stat:
      path: /usr/include/freetype2/freetype
    register: freetype2_dir

  - name: Fix link to freetype2
    become: yes
    file:
      state: link
      src: /usr/include/freetype2
      dest: /usr/include/freetype2/freetype
    when: freetype2_dir.stat.exists == False

  - name: Create virtualenv
    command: virtualenv -p /usr/bin/python2.7 /home/vagrant/py27 creates=/home/vagrant/py27/
    become: no

  - name: Upgrade setuptools and pip
    become: no
    pip:
        state: latest
        name: pip

  - name: Download Kofa sources with pip
    become: no
    command: /home/vagrant/py27/bin/pip download --no-deps waeup.kofa=={{ kofa_version }}
    args:
      chdir: /home/vagrant
      creates: /home/vagrant/waeup.kofa-{{ kofa_version }}

  - name: Unpack Kofa sources
    become: no
    unarchive:
      copy: no
      src: /home/vagrant/waeup.kofa-{{ kofa_version }}.tar.gz
      dest: /home/vagrant/

  - name: Run bootstrap
    become: no
    command: /home/vagrant/py27/bin/python bootstrap.py
    args:
      chdir: /home/vagrant/waeup.kofa-{{ kofa_version }}
      creates: /home/vagrant/waeup.kofa-{{ kofa_version }}/bin/buildout

  - name: Run buildout (this may take some minutes...)
    become: no
    command: /home/vagrant/waeup.kofa-{{ kofa_version }}/bin/buildout
    args:
      chdir: /home/vagrant/waeup.kofa-{{ kofa_version }}
      creates: /home/vagrant/waeup.kofa-{{ kofa_version }}/bin/kofactl
