---
- hosts: all
  become: yes
  remote_user: root
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400

  - name: Aptitude safe-upgrade
    apt: upgrade=safe
